-- Table UTILISATEUR
CREATE TABLE UTILISATEUR (
    idU INTEGER NOT NULL,
    isAdmin INTEGER NOT NULL,
    pseudo TEXT NOT NULL UNIQUE,
    mdp TEXT NOT NULL,
    adresseMail TEXT,
    PRIMARY KEY(idU AUTOINCREMENT)
);

-- Table GENRE
CREATE TABLE GENRE (
    idG INTEGER NOT NULL,
    nomG INTEGER NOT NULL UNIQUE,
    PRIMARY KEY(idG AUTOINCREMENT)
);

-- Table ARTISTES
CREATE TABLE ARTISTES (
    idA INTEGER NOT NULL,
    nomA TEXT NOT NULL,
    PRIMARY KEY(idA)
);

-- Table MUSIQUES
CREATE TABLE MUSIQUES (
    id INTEGER NOT NULL,
    img BLOB,
    dateDeSortie INTEGER NOT NULL,
    titre TEXT NOT NULL,
    idCompositeur INTEGER NOT NULL,
    idInterprete INTEGER NOT NULL,
    FOREIGN KEY(idCompositeur) REFERENCES ARTISTES(idA),
    FOREIGN KEY(idInterprete) REFERENCES ARTISTES(idA),
    PRIMARY KEY(id)
);

-- Table ETRE
CREATE TABLE ETRE (
    idM INTEGER NOT NULL,
    idG INTEGER NOT NULL,
    FOREIGN KEY(idG) REFERENCES GENRE(idG),
    FOREIGN KEY(idM) REFERENCES MUSIQUES(id),
    PRIMARY KEY(idM, idG)
);

-- Table FAVORIS
CREATE TABLE FAVORIS (
    idU INTEGER NOT NULL,
    idM INTEGER NOT NULL,
    FOREIGN KEY(idM) REFERENCES MUSIQUES(id),
    FOREIGN KEY(idU) REFERENCES UTILISATEUR(idU),
    PRIMARY KEY(idU, idM)
);
