CREATE TABLE "UTILISATEUR" (
	"idU"	INTEGER NOT NULL,
	"isAdmin"	INTEGER NOT NULL,
	"pseudo"	TEXT NOT NULL UNIQUE,
	"mdp"	TEXT NOT NULL,
	"adresseMail"	TEXT,
	PRIMARY KEY("idU" AUTOINCREMENT)
);

CREATE TABLE "GENRE" (
	"idG"	INTEGER NOT NULL,
	"nomG"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("idG" AUTOINCREMENT)
);

CREATE TABLE "ARTISTES" (
	"idA"	INTEGER NOT NULL,
	"nomA"	TEXT NOT NULL,
	PRIMARY KEY("idA")
);

CREATE TABLE "ALBUMS" (
	"id"	INTEGER NOT NULL,
	"img"	BLOB,
	"dateDeSortie"	INTEGER NOT NULL,
	"titre"	TEXT NOT NULL,
	"idCompositeur"	INTEGER NOT NULL,
	"idInterprete"	INTEGER NOT NULL,
	FOREIGN KEY("idInterprete") REFERENCES "ARTISTES"("idA"),
	PRIMARY KEY("id"),
	FOREIGN KEY("idCompositeur") REFERENCES "ARTISTES"("idA")
);

CREATE TABLE "ETRE" (
	"idAl"	INTEGER NOT NULL,
	"idG"	INTEGER NOT NULL,
	FOREIGN KEY("idG") REFERENCES "GENRE"("idG"),
	FOREIGN KEY("idAl") REFERENCES "ALBUMS"("id"),
	PRIMARY KEY("idAl","idG")
);

CREATE TABLE "FAVORIS" (
	"idU"	INTEGER NOT NULL,
	"idAl"	INTEGER NOT NULL,
	FOREIGN KEY("idAl") REFERENCES "ALBUMS"("id"),
	FOREIGN KEY("idU") REFERENCES "UTILISATEUR"("idU"),
	PRIMARY KEY("idU","idAl")
);

